version: '3.8'

services:
  app:
    container_name: fiap-billing
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_WEBHOOK_SECRET=${MP_WEBHOOK_SECRET}
      - MP_NOTIFICATION_URL=${MP_NOTIFICATION_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - OS_SERVICE_URL=${OS_SERVICE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE:-payment-events}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-billing-queue}
    depends_on:
      - mongo
      - mailhog
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default
      - fiap-net

  mongo:
    image: mongo:7
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"

volumes:
  mongo_data:

networks:
  fiap-net:
    external: true
